services:
  kafka:
    image: quay.io/debezium/kafka:3.5
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: hiepnh
      NODE_ID: 1
      NODE_ROLE: combined
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    networks:
      - debezium-net

  mysql:
    image: quay.io/debezium/example-mysql:3.5
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
    networks:
      - debezium-net

  connect:
    image: quay.io/debezium/connect:3.5
    container_name: connect
    hostname: connect
    ports:
      - "8083:8083"
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
      - mysql
    networks:
      - debezium-net

  watcher:
    image: quay.io/debezium/kafka:3.5
    container_name: watcher
    hostname: watcher
    command: ["watch-topic", "-a", "-k", "dbserver1.inventory.customers"]
    depends_on:
      - kafka
    networks:
      - debezium-net

networks:
  debezium-net:
    driver: bridge
